map2d_png_files = files(
    'ina_01.png',
    'ina_01p.png',
    'mr01b07_mn.png',
    'mr01i19_mn.png',
    'mr01i27_mn.png',
    'mr01i29_mn.png',
    'mr02b02_mn.png',
    'mr02b03_mn.png',
    'mr02b04_mn.png',
    'mr02b05_mn.png',
    'mr02b07_mn.png',
    'mr02b08_mn.png',
    'mr02b09_mn.png',
    'mr02b10_mn.png',
    'mr02b11_mn.png',
    'mr02b12_mn.png',
    'mr02b13_mn.png',
    'mr02b15_mn.png',
    'mr02b91_mn.png',
    'mr02i01_mn.png',
    'mr02i02_mn.png',
    'mr02i03_mn.png',
    'mr02i04_mn.png',
    'mr02i05_mn.png',
    'mr02i06_mn.png',
    'mr02i07_mn.png',
    'mr02i08_mn.png',
    'mr02i11_mn.png',
    'mr02i12_mn.png',
    'mr02i13_mn.png',
    'mr02i14_mn.png',
    'mr03b01_mn.png',
    'mr03i01_mn.png',
    'mr07b03_mn.png',
    'mr07i01_mn.png',
    'mr07i02_mn.png',
    'mr07i03_mn.png',
    'mr07i06_mn.png',
    'mr08b01_mn.png',
    'mr09b01_mn.png',
    'mr09b02_mn.png',
    'mr09b03_mn.png',
    'mr09b04_mn.png',
    'mr09i01_mn.png',
    'mr09i02_mn.png',
    'mr09i03_mn.png',
    'mr10b01_mn.png',
    'mr10b02_mn.png',
    'mr10b03_mn.png',
    'mr10b05_mn.png',
    'mr10b06_mn.png',
    'mr10b07_mn.png',
    'mr10b08_mn.png',
    'mr10i01_mn.png',
    'mr10i02_mn.png',
    'mr10i03_mn.png',
    'mr11b01_mn.png',
    'mr11b02_mn.png',
    'mr11b03_mn.png',
    'mr11i02_mn.png',
    'mr11i03_mn.png',
    'mr12b02_mn.png',
    'mr12b03_mn.png',
    'mr12b06_mn.png',
    'mr12i01_mn.png',
    'mr12i02_mn.png',
    'mr13b01_mn.png',
    'mr13b02_mn.png',
    'mr13b03_mn.png',
    'mr13b04_mn.png',
    'mr13b05_mn.png',
    'mr13i01_mn.png',
    'mr13i02_mn.png',
    'mr13i03_mn.png',
    'mr13i04_mn.png',
    'mr14b01_mn.png',
    'mr14b02_mn.png',
    'mr14i01_mn.png',
    'mr14i03_mn.png',
    'mr15b01_mn.png',
    'mr15b03_mn.png',
    'mr15b04_mn.png',
    'mr15i01_mn.png',
    'mr15i02_mn.png',
    'mr15i03_mn.png',
    'mr15i05_mn.png',
    'mr15i06_mn.png',
    'mr16b01_mn.png',
    'mr16b02_mn.png',
    'mr16b03_mn.png',
    'mr16b04_mn.png',
    'mr16b05_mn.png',
    'mr16b06_mn.png',
    'mr16b07_mn.png',
    'mr16b08_mn.png',
    'mr16b09_mn.png',
    'mr16b10_mn.png',
    'mr16b11_mn.png',
    'mr16b12_mn.png',
    'mr16b13_mn.png',
    'mr16b14_mn.png',
    'mr16b15_mn.png',
    'mr16b16_mn.png',
    'mr16b17_mn.png',
    'mr16b18_mn.png',
    'mr16b19_mn.png',
    'mr16b20_mn.png',
    'mr16b21_mn.png',
    'mr16b22_mn.png',
    'mr16b23_mn.png',
    'mr16b24_mn.png',
    'mr16b25_mn.png',
    'mr16b26_mn.png',
    'mr16b27_mn.png',
    'mr16b28_mn.png',
    'mr16b29_mn.png',
    'mr16b30_mn.png',
    'mr16b31_mn.png',
    'mr16b32_mn.png',
    'mr16b33_mn.png',
    'mr16b34_mn.png',
    'mr16b35_mn.png',
    'mr16b36_mn.png',
    'mr16b37_mn.png',
    'mr16b38_mn.png',
    'mr16b39_mn.png',
    'mr16b40_mn.png',
    'mr16b99_mn.png',
    'mr16i05_mn.png',
    'mr16i06_mn.png',
    'mr16i07_mn.png',
    'mr16i09_mn.png',
    'mr16i10_mn.png',
    'mr16i11_mn.png',
    'mr16i12_mn.png',
    'mr16i13_mn.png',
    'mr16i14_mn.png',
    'mr16i15_mn.png',
    'mr16i16_mn.png',
    'mr16i17_mn.png',
    'mr16i18_mn.png',
    'mr16i19_mn.png',
    'mr16i20_mn.png',
    'mr16i21_mn.png',
    'mr16i22_mn.png',
    'mr16i23_mn.png',
    'mr16i24_mn.png',
    'mr16i25_mn.png',
    'mr16i26_mn.png',
    'mr16i27_mn.png',
    'mr16i28_mn.png',
    'mr16i29_mn.png',
    'mr16i30_mn.png',
    'mr16i31_mn.png',
    'mr16i32_mn.png',
    'mr16i33_mn.png',
    'mr16i34_mn.png',
    'mr16i35_mn.png',
    'mr16i36_mn.png',
    'mr16i37_mn.png',
    'mr16i38_mn.png',
    'mr16i39_mn.png',
    'mr16i40_mn.png',
    'mr19b01_mn.png',
    'mr19b02_mn.png',
    'mr19b03_mn.png',
    'mr19i01_mn.png',
    'mr19i02_mn.png',
    'mr19i03_mn.png',
    'mr19i04_mn.png',
    'mr19i05_mn.png',
    'mr19i06_mn.png',
    'mr19i07_mn.png',
    'mr19i08_mn.png',
    'mr20b01_mn.png',
    'mr20b02_mn.png',
    'mr20b03_mn.png',
    'mr20b04_mn.png',
    'mr20b05_mn.png',
    'mr20b06_mn.png',
    'mr20i01_mn.png',
    'mr20i02_mn.png',
    'mr20i03_mn.png',
    'mr20i04_mn.png',
    'mr20i05_mn.png',
    'mr20i06_mn.png',
    'mr20i07_mn.png',
    'mr21b01_mn.png',
    'mr21b02_mn.png',
    'mr21b03_mn.png',
    'mr21b04_mn.png',
    'mr21b05_mn.png',
    'mr21i01_mn.png',
    'mr21i02_mn.png',
    'mr21i03_mn.png',
    'mr21i04_mn.png',
    'mr21i05_mn.png',
    'mr21i06_mn.png',
    'mr21i07_mn.png',
    'mr21i08_mn.png',
    'mr21i10_mn.png',
    'mr22b01_mn.png',
    'mr22b02_mn.png',
    'mr22i01_mn.png',
    'mr22i02_mn.png',
    'mr22i03_mn.png',
    'mr22i04_mn.png',
    'mr22i05_mn.png',
    'mr23b01_mn.png',
    'mr23b02_mn.png',
    'mr23i01_mn.png',
    'mr23i02_mn.png',
    'mr24b01_mn.png',
    'mr24b02_mn.png',
    'mr24b04_mn.png',
    'mr24i01_mn.png',
    'mr24i02_mn.png',
    'mr24i03_mn.png',
    'mr25b01_mn.png',
    'mr25b02_mn.png',
    'mr25b03_mn.png',
    'mr25i01_mn.png',
    'mr25i02_mn.png',
    'mr25i03_mn.png',
    'mr26b01_mn.png',
    'mr26b02_mn.png',
    'mr26b03_mn.png',
    'mr26i01_mn.png',
    'mr26i02_mn.png',
    'mr26i03_mn.png',
    'mr27b01_mn.png',
    'mr27b02_mn.png',
    'mr27b03_mn.png',
    'mr27i01_mn.png',
    'mr27i02_mn.png',
    'mr27i03_mn.png',
    'mr28b01_mn.png',
    'mr28b02_mn.png',
    'mr28i01_mn.png',
    'mr28i02_mn.png',
    'mr29b04_mn.png',
    'mr29b05_mn.png',
    'mr29b11_mn.png',
    'mr29b12_mn.png',
    'mr29b13_mn.png',
    'mr29b14_mn.png',
    'mr29b15_mn.png',
    'mr29i01_mn.png',
    'mr30b05_mn.png',
    'mr30b06_mn.png',
    'mr30b11_mn.png',
    'mr30b12_mn.png',
    'mr30b13_mn.png',
    'mr30b14_mn.png',
    'mr30b15_mn.png',
    'mr30b16_mn.png',
    'mr30i01_mn.png',
    'mr31b05_mn.png',
    'mr31b06_mn.png',
    'mr31b11_mn.png',
    'mr31b12_mn.png',
    'mr31b13_mn.png',
    'mr31b14_mn.png',
    'mr31b15_mn.png',
    'mr31b16_mn.png',
    'mr31i01_mn.png',
    'mr32b06_mn.png',
    'mr32b07_mn.png',
    'mr32b11_mn.png',
    'mr32b12_mn.png',
    'mr32b13_mn.png',
    'mr32b14_mn.png',
    'mr32b15_mn.png',
    'mr32b16_mn.png',
    'mr32b17_mn.png',
    'mr32i01_mn.png',
    'mr33b07_mn.png',
    'mr33b08_mn.png',
    'mr33b11_mn.png',
    'mr33b12_mn.png',
    'mr33b13_mn.png',
    'mr33b14_mn.png',
    'mr33b15_mn.png',
    'mr33b16_mn.png',
    'mr33b17_mn.png',
    'mr33b18_mn.png',
    'mr33b19_mn.png',
    'mr33b20_mn.png',
    'mr33i01_mn.png',
    'mr34b01_mn.png',
    'mr34b11_mn.png',
    'mr34b12_mn.png',
    'mr34b13_mn.png',
    'mr34b14_mn.png',
    'mr34b15_mn.png',
    'mr34b16_mn.png',
    'mr34b17_mn.png',
    'mr34b18_mn.png',
    'mr34b19_mn.png',
    'mr34b20_mn.png',
    'mr34b21_mn.png',
    'mr34i01_mn.png',
    'mr35b01_mn.png',
    'mr35b11_mn.png',
    'mr35b12_mn.png',
    'mr35i02_mn.png',
    'mr88b01_mn.png',
    'mr88b02_mn.png',
    'mr88b03_mn.png',
    'mr88b40_mn.png',
    'mr88b41_mn.png',
    'mr88b42_mn.png',
    'mr88b51_mn.png',
    'mr88i01_mn.png',
    'mr88i02_mn.png',
    'mr88i08_mn.png',
    'mr88i09_mn.png',
    'mr88i10_mn.png',
    'mr88i11_mn.png',
    'mr88i21_mn.png',
    'mr88i22_mn.png',
    'mr88i23_mn.png',
    'mr88i24_mn.png',
    'mr88i99_mn.png',
    'mr99i03_mn.png',
)

map2d_pac_files = []

python3 = find_program('python3')

foreach map2d_png : map2d_png_files
    pac = custom_target(fs.name(map2d_png).replace('.png', '.pac_'),
        input: map2d_png,
        output: '@BASENAME@.pac_',
        command: [
            python3,
            image_py,
            '@INPUT@',
            '-t', 'PSC',
            '-c', '@OUTPUT@',
        ]
    )
    map2d_pac_files += pac
endforeach
