NITROFS_FILES := \
	files/data_iz/DEBUG_BGM_LIST.txt \
	files/data_iz/DEBUG_MAPJUMP_LIST.TXT \
	files/data_iz/DEBUG_SCRIPT_LIST.txt \
	files/data_iz/EVENTINFO.TXT \
	files/data_iz/INAZUMA.INI \
	files/data_iz/MCSFILE.TXT \
	files/data_iz/ROM_TIME.TXT \
	files/data_iz/SCRIPTINFO.TXT \
	files/data_iz/SCRIPTINFOMAP.TXT \
	files/data_iz/bfmt/cnvdat.bin \
	files/data_iz/bfmt/ver0000.bin \
	files/data_iz/bfmt/ver0001.bin \
	files/data_iz/bfmt/ver0002.bin \
	files/data_iz/bfmt/ver0003.bin \
	files/data_iz/bfmt/ver0004.bin \
	files/data_iz/bfmt/ver0005.bin \
	files/data_iz/bfmt/ver0006.bin \
	files/data_iz/bfmt/ver0007.bin \
	files/data_iz/bfmt/ver0008.bin \
	files/data_iz/bfmt/ver0009.bin \
	files/data_iz/bfmt/ver0010.bin \
	files/data_iz/bfmt/ver0011.bin \
	files/data_iz/bfmt/ver0012.bin \
	files/data_iz/bfmt/ver0013.bin \
	files/data_iz/bfmt/ver0014.bin \
	files/data_iz/bfmt/ver0015.bin \
	files/data_iz/bfmt/ver0016.bin \
	files/data_iz/bfmt/ver0017.bin \
	files/data_iz/bfmt/ver0018.bin \
	files/data_iz/bfmt/ver0019.bin \
	files/data_iz/bfmt/ver0020.bin \
	files/data_iz/bfmt/ver0021.bin \
	files/data_iz/bfmt/ver0022.bin \
	files/data_iz/bfmt/ver0023.bin \
	files/data_iz/bfmt/ver0024.bin \
	files/data_iz/bfmt/ver0025.bin \
	files/data_iz/bfmt/ver0026.bin \
	files/data_iz/bfmt/ver0027.bin \
	files/data_iz/bfmt/ver0028.bin \
	files/data_iz/bfmt/ver0029.bin \
	files/data_iz/bfmt/ver0030.bin \
	files/data_iz/bfmt/ver0031.bin \
	files/data_iz/bfmt/ver0032.bin \
	files/data_iz/bfmt/ver0033.bin \
	files/data_iz/bfmt/ver0034.bin \
	files/data_iz/bfmt/ver0035.bin \
	files/data_iz/effect3d/eff.pkb \
	files/data_iz/effect3d/eff.pkh \
	files/data_iz/face2d/fab.pkb \
	files/data_iz/face2d/fab.pkh \
	files/data_iz/face2d/fac.pkb \
	files/data_iz/face2d/fac.pkh \
	files/data_iz/face2d/ppu.pkb \
	files/data_iz/face2d/ppu.pkh \
	files/data_iz/font/FONT12.NFTR \
	files/data_iz/font/FONT12T.NFTR \
	files/data_iz/font/FONT8.NFTR \
	files/data_iz/font/RUBI8.NFTR \
	files/data_iz/logic/action.dat \
	files/data_iz/logic/BattleRouteTitle.dat \
	files/data_iz/logic/bgm_collection.bin \
	files/data_iz/logic/BinderData_AREA.dat \
	files/data_iz/logic/BinderData_O.dat \
	files/data_iz/logic/calcbase.dat \
	files/data_iz/logic/CapsuleComment.dat \
	files/data_iz/logic/CapsulePoint.dat \
	files/data_iz/logic/clbonus.dat \
	files/data_iz/logic/ClearCondition.dat \
	files/data_iz/logic/clubinfo.dat \
	files/data_iz/logic/cmd_cond.dat \
	files/data_iz/logic/command.dat \
	files/data_iz/logic/command.STR \
	files/data_iz/logic/command_price.dat \
	files/data_iz/logic/d_bonus_exp.dat \
	files/data_iz/logic/ed_option_f.dat \
	files/data_iz/logic/fieldinf.dat \
	files/data_iz/logic/fieldsel.dat \
	files/data_iz/logic/fmt.pkb \
	files/data_iz/logic/fmt.pkh \
	files/data_iz/logic/fmtsm.dat \
	files/data_iz/logic/gamerule.dat \
	files/data_iz/logic/games.dat \
	files/data_iz/logic/games.STR \
	files/data_iz/logic/gloveinfo.dat \
	files/data_iz/logic/gmap01_SPD.dat \
	files/data_iz/logic/gmap02_SPD.dat \
	files/data_iz/logic/gmap03_SPD.dat \
	files/data_iz/logic/gmap04_SPD.dat \
	files/data_iz/logic/gmap05_SPD.dat \
	files/data_iz/logic/gmap06_SPD.dat \
	files/data_iz/logic/gmap07_SPD.dat \
	files/data_iz/logic/gmap08_SPD.dat \
	files/data_iz/logic/gmap09_SPD.dat \
	files/data_iz/logic/gmap10_SPD.dat \
	files/data_iz/logic/gmap11_SPD.dat \
	files/data_iz/logic/gmap12_SPD.dat \
	files/data_iz/logic/gmap13_SPD.dat \
	files/data_iz/logic/gmap14_SPD.dat \
	files/data_iz/logic/gmap15_SPD.dat \
	files/data_iz/logic/gmap16_SPD.dat \
	files/data_iz/logic/gmap17_SPD.dat \
	files/data_iz/logic/gmap18_SPD.dat \
	files/data_iz/logic/gmap19_SPD.dat \
	files/data_iz/logic/gmap20_SPD.dat \
	files/data_iz/logic/gmap21_SPD.dat \
	files/data_iz/logic/gmap22_SPD.dat \
	files/data_iz/logic/gmap23_SPD.dat \
	files/data_iz/logic/gmap24_SPD.dat \
	files/data_iz/logic/gmap25_SPD.dat \
	files/data_iz/logic/gmap_draw_info_01.dat \
	files/data_iz/logic/gmap_draw_info_02.dat \
	files/data_iz/logic/gmap_draw_info_03.dat \
	files/data_iz/logic/gmap_draw_info_04.dat \
	files/data_iz/logic/gmap_draw_info_05.dat \
	files/data_iz/logic/gmap_draw_info_06.dat \
	files/data_iz/logic/gmap_draw_info_07.dat \
	files/data_iz/logic/gmap_draw_info_08.dat \
	files/data_iz/logic/gmap_draw_info_09.dat \
	files/data_iz/logic/gmap_draw_info_10.dat \
	files/data_iz/logic/gmap_draw_info_11.dat \
	files/data_iz/logic/gmap_draw_info_12.dat \
	files/data_iz/logic/gmap_draw_info_13.dat \
	files/data_iz/logic/gmap_draw_info_14.dat \
	files/data_iz/logic/gmap_draw_info_15.dat \
	files/data_iz/logic/gmap_draw_info_16.dat \
	files/data_iz/logic/gmap_draw_info_17.dat \
	files/data_iz/logic/gmap_draw_info_18.dat \
	files/data_iz/logic/gmap_draw_info_19.dat \
	files/data_iz/logic/gmap_draw_info_20.dat \
	files/data_iz/logic/gmap_draw_info_21.dat \
	files/data_iz/logic/gmap_draw_info_22.dat \
	files/data_iz/logic/gmap_draw_info_23.dat \
	files/data_iz/logic/gmap_draw_info_24.dat \
	files/data_iz/logic/gmap_draw_info_25.dat \
	files/data_iz/logic/gmap_load_info.dat \
	files/data_iz/logic/HeadhuntData.dat \
	files/data_iz/logic/HeadhuntList.dat \
	files/data_iz/logic/i_detail.dat \
	files/data_iz/logic/i_limit.dat \
	files/data_iz/logic/item.dat \
	files/data_iz/logic/item.STR \
	files/data_iz/logic/item_md.dat \
	files/data_iz/logic/item_pw_adhoc.dat \
	files/data_iz/logic/itemsortlist.dat \
	files/data_iz/logic/JinmyakuCursor.dat \
	files/data_iz/logic/JinmyakuData.dat \
	files/data_iz/logic/JinmyakuLV.dat \
	files/data_iz/logic/JinmyakuTreasure.dat \
	files/data_iz/logic/livetalk.dat \
	files/data_iz/logic/lvup_command.dat \
	files/data_iz/logic/lvup_exp.dat \
	files/data_iz/logic/mapidx.dat \
	files/data_iz/logic/missinfo.dat \
	files/data_iz/logic/MLPass.bin \
	files/data_iz/logic/movie_view_f.dat \
	files/data_iz/logic/OpenCondition.dat \
	files/data_iz/logic/palglove.dat \
	files/data_iz/logic/palshoes.dat \
	files/data_iz/logic/palskin2d.dat \
	files/data_iz/logic/palskin3d.dat \
	files/data_iz/logic/palskinface.dat \
	files/data_iz/logic/phone_password.txt \
	files/data_iz/logic/pintro.dat \
	files/data_iz/logic/PracticeDataF.dat \
	files/data_iz/logic/PracticeGame0F.dat \
	files/data_iz/logic/PracticeGame1F.dat \
	files/data_iz/logic/PracticeGame2F.dat \
	files/data_iz/logic/PracticeGame3F.dat \
	files/data_iz/logic/PracticeGame4F.dat \
	files/data_iz/logic/PracticeGame5F.dat \
	files/data_iz/logic/PracticeGame6F.dat \
	files/data_iz/logic/PracticeGame7F.dat \
	files/data_iz/logic/PracticeGame8F.dat \
	files/data_iz/logic/PracticeGame9F.dat \
	files/data_iz/logic/PracticeGameCursor.dat \
	files/data_iz/logic/premium_item.dat \
	files/data_iz/logic/premium_item_hurri.dat \
	files/data_iz/logic/premiumcondition.dat \
	files/data_iz/logic/premiumcondition_hurri.dat \
	files/data_iz/logic/rpgtitle.dat \
	files/data_iz/logic/rpgtitle.STR \
	files/data_iz/logic/schinfo.dat \
	files/data_iz/logic/ScoutData.dat \
	files/data_iz/logic/ScoutSpCode.dat \
	files/data_iz/logic/SetEndrollBG.dat \
	files/data_iz/logic/SetRestPoint.dat \
	files/data_iz/logic/shoesinfo.dat \
	files/data_iz/logic/shootchain.dat \
	files/data_iz/logic/shop.dat \
	files/data_iz/logic/ShopName.dat \
	files/data_iz/logic/sp_binder.dat \
	files/data_iz/logic/sp_binder.STR \
	files/data_iz/logic/status_up.dat \
	files/data_iz/logic/SystemMenuOrder.dat \
	files/data_iz/logic/tacticscmd.dat \
	files/data_iz/logic/tacticscmd.STR \
	files/data_iz/logic/team.pkb \
	files/data_iz/logic/team.pkh \
	files/data_iz/logic/teamtitle.dat \
	files/data_iz/logic/teamtpmax.dat \
	files/data_iz/logic/TokkunData.dat \
	files/data_iz/logic/TournamentItem01.dat \
	files/data_iz/logic/TournamentItem02.dat \
	files/data_iz/logic/TournamentItem03.dat \
	files/data_iz/logic/TournamentItem04.dat \
	files/data_iz/logic/TournamentItem05.dat \
	files/data_iz/logic/TournamentItem06.dat \
	files/data_iz/logic/TournamentItem07.dat \
	files/data_iz/logic/TournamentItem08.dat \
	files/data_iz/logic/TournamentItem09.dat \
	files/data_iz/logic/TournamentItem10.dat \
	files/data_iz/logic/TournamentItem11.dat \
	files/data_iz/logic/TournamentItem12.dat \
	files/data_iz/logic/TournamentItem13.dat \
	files/data_iz/logic/TournamentItem14.dat \
	files/data_iz/logic/TournamentItem15.dat \
	files/data_iz/logic/TournamentItem16.dat \
	files/data_iz/logic/TournamentName01.dat \
	files/data_iz/logic/TournamentName02.dat \
	files/data_iz/logic/TournamentName03.dat \
	files/data_iz/logic/TournamentName04.dat \
	files/data_iz/logic/TournamentName05.dat \
	files/data_iz/logic/TournamentName06.dat \
	files/data_iz/logic/TournamentName07.dat \
	files/data_iz/logic/TournamentName08.dat \
	files/data_iz/logic/TournamentName09.dat \
	files/data_iz/logic/TournamentName10.dat \
	files/data_iz/logic/TournamentName11.dat \
	files/data_iz/logic/TournamentName12.dat \
	files/data_iz/logic/TournamentName13.dat \
	files/data_iz/logic/TournamentName14.dat \
	files/data_iz/logic/TournamentName15.dat \
	files/data_iz/logic/TournamentName16.dat \
	files/data_iz/logic/TournamentRank.dat \
	files/data_iz/logic/TournamentRankPlus1.dat \
	files/data_iz/logic/TournamentRankPlus2.dat \
	files/data_iz/logic/TournamentRankPlus3.dat \
	files/data_iz/logic/TournamentTeam01.dat \
	files/data_iz/logic/TournamentTeam02.dat \
	files/data_iz/logic/TournamentTeam03.dat \
	files/data_iz/logic/TournamentTeam04.dat \
	files/data_iz/logic/TournamentTeam05.dat \
	files/data_iz/logic/TournamentTeam06.dat \
	files/data_iz/logic/TournamentTeam07.dat \
	files/data_iz/logic/TournamentTeam08.dat \
	files/data_iz/logic/TournamentTeam09.dat \
	files/data_iz/logic/TournamentTeam10.dat \
	files/data_iz/logic/TournamentTeam11.dat \
	files/data_iz/logic/TournamentTeam12.dat \
	files/data_iz/logic/TournamentTeam13.dat \
	files/data_iz/logic/TournamentTeam14.dat \
	files/data_iz/logic/TournamentTeam15.dat \
	files/data_iz/logic/TournamentTeam16.dat \
	files/data_iz/logic/TradeData.dat \
	files/data_iz/logic/unitbase.dat \
	files/data_iz/logic/unitbase.STR \
	files/data_iz/logic/unitbase_npc.dat \
	files/data_iz/logic/unitcalc.dat \
	files/data_iz/logic/unitchange.dat \
	files/data_iz/logic/unitno.dat \
	files/data_iz/logic/unitno_npc.dat \
	files/data_iz/logic/unitstat.dat \
	files/data_iz/logic/uschool.dat \
	files/data_iz/logic/usearch.dat \
	files/data_iz/logic/wearset.dat \
	files/data_iz/map2d/map2d.pkb \
	files/data_iz/map2d/map2d.pkh \
	files/data_iz/model/char/body_no.pac_ \
	files/data_iz/model/char/pbb.pkb \
	files/data_iz/model/char/pbb.pkh \
	files/data_iz/model/char/pbf.pkb \
	files/data_iz/model/char/pbf.pkh \
	files/data_iz/model/char/pbh.pkb \
	files/data_iz/model/char/pbh.pkh \
	files/data_iz/model/char/pbs.pkb \
	files/data_iz/model/char/pbs.pkh \
	files/data_iz/model/char/pcm.pkb \
	files/data_iz/model/char/pcm.pkh \
	files/data_iz/model/char/psb.pkb \
	files/data_iz/model/char/psb.pkh \
	files/data_iz/model/char/psf.pkb \
	files/data_iz/model/char/psf.pkh \
	files/data_iz/model/char/psh.pkb \
	files/data_iz/model/char/psh.pkh \
	files/data_iz/model/char/pss.pkb \
	files/data_iz/model/char/pss.pkh \
	files/data_iz/model/char/ptb.pkb \
	files/data_iz/model/char/ptb.pkh \
	files/data_iz/model/obj/ball0010.nsbmd_ \
	files/data_iz/model/obj/ball_nsbmd.pkb \
	files/data_iz/model/obj/ball_nsbmd.pkh \
	files/data_iz/model/obj/gol_nsbmd.pkb \
	files/data_iz/model/obj/gol_nsbmd.pkh \
	files/data_iz/model/obj/mf_nsbmd.pkb \
	files/data_iz/model/obj/mf_nsbmd.pkh \
	files/data_iz/model/obj/mo_nsbmd.pkb \
	files/data_iz/model/obj/mo_nsbmd.pkh \
	files/data_iz/model/obj/mr_bcd.pkb \
	files/data_iz/model/obj/mr_bcd.pkh \
	files/data_iz/model/obj/mr_nsbmd.pkb \
	files/data_iz/model/obj/mr_nsbmd.pkh \
	files/data_iz/model/obj/mr_nsbtx.pkb \
	files/data_iz/model/obj/mr_nsbtx.pkh \
	files/data_iz/model/obj/mv_nsbmd.pkb \
	files/data_iz/model/obj/mv_nsbmd.pkh \
	files/data_iz/model/obj/mv_nsbtx.pkb \
	files/data_iz/model/obj/mv_nsbtx.pkh \
	files/data_iz/model/pac/bal_pac.pkb \
	files/data_iz/model/pac/bal_pac.pkh \
	files/data_iz/model/pac/cmr.pkb \
	files/data_iz/model/pac/cmr.pkh \
	files/data_iz/model/pac/gol_pac.pkb \
	files/data_iz/model/pac/gol_pac.pkh \
	files/data_iz/model/pac/mo_pac.pkb \
	files/data_iz/model/pac/mo_pac.pkh \
	files/data_iz/model/pac/mr_pac.pkb \
	files/data_iz/model/pac/mr_pac.pkh \
	files/data_iz/model/pac/mv_pac.pkb \
	files/data_iz/model/pac/mv_pac.pkh \
	files/data_iz/movie/a3m02a.mods \
	files/data_iz/movie/a3m03a.mods \
	files/data_iz/movie/a3m03b.mods \
	files/data_iz/movie/a3m04a.mods \
	files/data_iz/movie/a3m05a.mods \
	files/data_iz/movie/a3m05b.mods \
	files/data_iz/movie/a3m05c.mods \
	files/data_iz/movie/a3m05d.mods \
	files/data_iz/movie/a3m05e.mods \
	files/data_iz/movie/a3m05f.mods \
	files/data_iz/movie/a3m06a.mods \
	files/data_iz/movie/a3m07a.mods \
	files/data_iz/movie/a3m08a.mods \
	files/data_iz/movie/a3m09a.mods \
	files/data_iz/movie/a3m10a.mods \
	files/data_iz/movie/a3m11a.mods \
	files/data_iz/movie/a3m11b.mods \
	files/data_iz/movie/a3m12a.mods \
	files/data_iz/movie/a3m13a.mods \
	files/data_iz/movie/a3m14a.mods \
	files/data_iz/movie/a3m15a.mods \
	files/data_iz/movie/a3m16a.mods \
	files/data_iz/movie/a3m17a.mods \
	files/data_iz/movie/a3m18a.mods \
	files/data_iz/movie/a3m19a.mods \
	files/data_iz/movie/a3m20a.mods \
	files/data_iz/movie/a3m21a.mods \
	files/data_iz/movie/a3m22a.mods \
	files/data_iz/movie/a3m23a.mods \
	files/data_iz/movie/a3m24a.mods \
	files/data_iz/movie/a3m25a.mods \
	files/data_iz/movie/a3m26a.mods \
	files/data_iz/movie/a3m27a.mods \
	files/data_iz/movie/a3m28a.mods \
	files/data_iz/movie/a3m29a.mods \
	files/data_iz/movie/a3m30a.mods \
	files/data_iz/movie/a3m31a.mods \
	files/data_iz/movie/a3m32a.mods \
	files/data_iz/movie/a3m33a.mods \
	files/data_iz/movie/a3m34a.mods \
	files/data_iz/movie/a3m35a.mods \
	files/data_iz/movie/a3m36a.mods \
	files/data_iz/movie/a3m37a.mods \
	files/data_iz/movie/a3m38a.mods \
	files/data_iz/movie/a3m39a.mods \
	files/data_iz/movie/a3m40a.mods \
	files/data_iz/movie/a3m41a.mods \
	files/data_iz/movie/a3m42a.mods \
	files/data_iz/movie/a3m43a.mods \
	files/data_iz/movie/a3m45a.mods \
	files/data_iz/movie/a3m46a.mods \
	files/data_iz/movie/a3m81a.mods \
	files/data_iz/movie/a3m82a.mods \
	files/data_iz/movie/a3m83a.mods \
	files/data_iz/movie/a3m84a.mods \
	files/data_iz/movie/a3m85a.mods \
	files/data_iz/movie/a3y01f.mods \
	files/data_iz/movie/a3y02f.mods \
	files/data_iz/movie/a3y03f.mods \
	files/data_iz/movie/a3y04f.mods \
	files/data_iz/movie/op00f.mods \
	files/data_iz/movie/pv_o1.mods \
	files/data_iz/movie/pv_o2.mods \
	files/data_iz/movie/txt/a3m02a.dat \
	files/data_iz/movie/txt/a3m03a.dat \
	files/data_iz/movie/txt/a3m03b.dat \
	files/data_iz/movie/txt/a3m04a.dat \
	files/data_iz/movie/txt/a3m05a.dat \
	files/data_iz/movie/txt/a3m05b.dat \
	files/data_iz/movie/txt/a3m05c.dat \
	files/data_iz/movie/txt/a3m05d.dat \
	files/data_iz/movie/txt/a3m05e.dat \
	files/data_iz/movie/txt/a3m05f.dat \
	files/data_iz/movie/txt/a3m06a.dat \
	files/data_iz/movie/txt/a3m07a.dat \
	files/data_iz/movie/txt/a3m08a.dat \
	files/data_iz/movie/txt/a3m09a.dat \
	files/data_iz/movie/txt/a3m10a.dat \
	files/data_iz/movie/txt/a3m11a.dat \
	files/data_iz/movie/txt/a3m11b.dat \
	files/data_iz/movie/txt/a3m12a.dat \
	files/data_iz/movie/txt/a3m13a.dat \
	files/data_iz/movie/txt/a3m14a.dat \
	files/data_iz/movie/txt/a3m15a.dat \
	files/data_iz/movie/txt/a3m16a.dat \
	files/data_iz/movie/txt/a3m17a.dat \
	files/data_iz/movie/txt/a3m18a.dat \
	files/data_iz/movie/txt/a3m19a.dat \
	files/data_iz/movie/txt/a3m20a.dat \
	files/data_iz/movie/txt/a3m21a.dat \
	files/data_iz/movie/txt/a3m22a.dat \
	files/data_iz/movie/txt/a3m23a.dat \
	files/data_iz/movie/txt/a3m24a.dat \
	files/data_iz/movie/txt/a3m25a.dat \
	files/data_iz/movie/txt/a3m27a.dat \
	files/data_iz/movie/txt/a3m28a.dat \
	files/data_iz/movie/txt/a3m30a.dat \
	files/data_iz/movie/txt/a3m32a.dat \
	files/data_iz/movie/txt/a3m33a.dat \
	files/data_iz/movie/txt/a3m35a.dat \
	files/data_iz/movie/txt/a3m36a.dat \
	files/data_iz/movie/txt/a3m38a.dat \
	files/data_iz/movie/txt/a3m39a.dat \
	files/data_iz/movie/txt/a3m40a.dat \
	files/data_iz/movie/txt/a3m41a.dat \
	files/data_iz/movie/txt/a3m42a.dat \
	files/data_iz/movie/txt/a3m43a.dat \
	files/data_iz/movie/txt/a3m45a.dat \
	files/data_iz/movie/txt/a3m81a.dat \
	files/data_iz/movie/txt/a3m82a.dat \
	files/data_iz/movie/txt/a3m83a.dat \
	files/data_iz/movie/txt/a3m84a.dat \
	files/data_iz/movie/txt/a3m85a.dat \
	files/data_iz/movie/txt/op00f.dat \
	files/data_iz/obj2d/rpg/ina_tpx1.pac_ \
	files/data_iz/obj2d/rpg/ina_tpx2.pac_ \
	files/data_iz/obj2d/rpg/ina_tpx3.pac_ \
	files/data_iz/obj2d/rpg/ina_tpx4.pac_ \
	files/data_iz/obj2d/rpg/ina_tpx5.pac_ \
	files/data_iz/obj2d/rpg/ina_tpx6.pac_ \
	files/data_iz/obj2d/rpg/ina_tpx7.pac_ \
	files/data_iz/obj2d/rpg/ina_tpx8.pac_ \
	files/data_iz/obj2d/rpg/mlup_filter.pac_ \
	files/dwc/utility.bin

.PHONY: filesystem
filesystem: $(NITROFS_FILES)