fab_png_files = files(
    'fab01010000.png',
    'fab01010001.png',
    'fab01010004.png',
    'fab01010005.png',
    'fab01010100.png',
    'fab01010102.png',
    'fab01010200.png',
    'fab01020000.png',
    'fab01020001.png',
    'fab01020004.png',
    'fab01020005.png',
    'fab01020100.png',
    'fab01020102.png',
    'fab01020200.png',
    'fab01480000.png',
    'fab01490000.png',
    'fab01500000.png',
    'fab01510000.png',
    'fab01520004.png',
    'fab01530000.png',
    'fab01530100.png',
    'fab01540000.png',
    'fab01550000.png',
    'fab01560102.png',
    'fab01570005.png',
    'fab01580005.png',
    'fab01590000.png',
    'fab01600000.png',
    'fab01600001.png',
    'fab01600004.png',
    'fab01600005.png',
    'fab01600100.png',
    'fab01600102.png',
    'fab01600200.png',
    'fab01650001.png',
    'fab01700005.png',
    'fab01700200.png',
    'fab01710005.png',
    'fab01720000.png',
    'fab01720004.png',
    'fab01730005.png',
    'fab01740000.png',
    'fab01750000.png',
    'fab01750001.png',
    'fab01750004.png',
    'fab01750005.png',
    'fab01750100.png',
    'fab01750102.png',
    'fab01750200.png',
    'fab01760005.png',
    'fab01770005.png',
    'fab01800000.png',
    'fab01900000.png',
    'fab01900001.png',
    'fab01900004.png',
    'fab01900005.png',
    'fab01900100.png',
    'fab01900102.png',
    'fab01900200.png',
    'fab01910000.png',
    'fab01910001.png',
    'fab01910004.png',
    'fab01910005.png',
    'fab01910100.png',
    'fab01910102.png',
    'fab01910200.png',
    'fab01920000.png',
    'fab01920001.png',
    'fab01920004.png',
    'fab01920005.png',
    'fab01920100.png',
    'fab01920102.png',
    'fab01920200.png',
    'fab01930000.png',
    'fab01930001.png',
    'fab01930004.png',
    'fab01930005.png',
    'fab01930100.png',
    'fab01930102.png',
    'fab01930200.png',
    'fab01940000.png',
    'fab01940001.png',
    'fab01940004.png',
    'fab01940005.png',
    'fab01940100.png',
    'fab01940102.png',
    'fab01940200.png',
    'fab01950000.png',
    'fab01950001.png',
    'fab01950004.png',
    'fab01950005.png',
    'fab01950100.png',
    'fab01950102.png',
    'fab01950200.png',
    'fab01960000.png',
    'fab01960001.png',
    'fab01960004.png',
    'fab01960005.png',
    'fab01960100.png',
    'fab01960102.png',
    'fab01960200.png',
    'fab01970000.png',
    'fab01970001.png',
    'fab01970004.png',
    'fab01970005.png',
    'fab01970100.png',
    'fab01970102.png',
    'fab01970200.png',
    'fab02010000.png',
    'fab02010001.png',
    'fab02010004.png',
    'fab02010005.png',
    'fab02010100.png',
    'fab02010102.png',
    'fab02010200.png',
    'fab02020000.png',
    'fab02020001.png',
    'fab02020004.png',
    'fab02020005.png',
    'fab02020100.png',
    'fab02020102.png',
    'fab02020200.png',
    'fab02980000.png',
    'fab02980001.png',
    'fab02980004.png',
    'fab02980100.png',
    'fab02980102.png',
    'fab02980200.png',
    'fab03010000.png',
    'fab03010001.png',
    'fab03010004.png',
    'fab03010005.png',
    'fab03010100.png',
    'fab03010102.png',
    'fab03010200.png',
    'fab03020000.png',
    'fab03020001.png',
    'fab03020004.png',
    'fab03020005.png',
    'fab03020100.png',
    'fab03020102.png',
    'fab03020200.png',
    'fab04010000.png',
    'fab04010001.png',
    'fab04010004.png',
    'fab04010005.png',
    'fab04010100.png',
    'fab04010102.png',
    'fab04010200.png',
    'fab04020000.png',
    'fab04020001.png',
    'fab04020004.png',
    'fab04020005.png',
    'fab04020100.png',
    'fab04020102.png',
    'fab04020200.png',
    'fab05010000.png',
    'fab05010001.png',
    'fab05010004.png',
    'fab05010005.png',
    'fab05010100.png',
    'fab05010102.png',
    'fab05010200.png',
    'fab05020000.png',
    'fab05020001.png',
    'fab05020004.png',
    'fab05020005.png',
    'fab05020100.png',
    'fab05020102.png',
    'fab05020200.png',
    'fab06010000.png',
    'fab06010001.png',
    'fab06010004.png',
    'fab06010005.png',
    'fab06010100.png',
    'fab06010102.png',
    'fab06010200.png',
    'fab06020000.png',
    'fab06020001.png',
    'fab06020004.png',
    'fab06020005.png',
    'fab06020100.png',
    'fab06020102.png',
    'fab06020200.png',
    'fab07010000.png',
    'fab07010001.png',
    'fab07010004.png',
    'fab07010005.png',
    'fab07010100.png',
    'fab07010102.png',
    'fab07010200.png',
    'fab07020000.png',
    'fab07020001.png',
    'fab07020004.png',
    'fab07020005.png',
    'fab07020100.png',
    'fab07020102.png',
    'fab07020200.png',
    'fab08010000.png',
    'fab08010001.png',
    'fab08010004.png',
    'fab08010005.png',
    'fab08010100.png',
    'fab08010102.png',
    'fab08010200.png',
    'fab08020000.png',
    'fab08020001.png',
    'fab08020004.png',
    'fab08020005.png',
    'fab08020100.png',
    'fab08020102.png',
    'fab08020200.png',
    'fab09010000.png',
    'fab09010001.png',
    'fab09010004.png',
    'fab09010005.png',
    'fab09010100.png',
    'fab09010102.png',
    'fab09010200.png',
    'fab09020000.png',
    'fab09020001.png',
    'fab09020004.png',
    'fab09020005.png',
    'fab09020100.png',
    'fab09020102.png',
    'fab09020200.png',
    'fab10010000.png',
    'fab10010001.png',
    'fab10010004.png',
    'fab10010005.png',
    'fab10010100.png',
    'fab10010102.png',
    'fab10010200.png',
    'fab10020000.png',
    'fab10020001.png',
    'fab10020004.png',
    'fab10020005.png',
    'fab10020100.png',
    'fab10020102.png',
    'fab10020200.png',
    'fab11010000.png',
    'fab11010001.png',
    'fab11010004.png',
    'fab11010005.png',
    'fab11010100.png',
    'fab11010102.png',
    'fab11010200.png',
    'fab11020000.png',
    'fab11020001.png',
    'fab11020004.png',
    'fab11020005.png',
    'fab11020100.png',
    'fab11020102.png',
    'fab11020200.png',
    'fab12010000.png',
    'fab12010001.png',
    'fab12010004.png',
    'fab12010005.png',
    'fab12010100.png',
    'fab12010102.png',
    'fab12010200.png',
    'fab12020000.png',
    'fab12020001.png',
    'fab12020004.png',
    'fab12020005.png',
    'fab12020100.png',
    'fab12020102.png',
    'fab12020200.png',
    'fab13010000.png',
    'fab13010001.png',
    'fab13010004.png',
    'fab13010005.png',
    'fab13010100.png',
    'fab13010102.png',
    'fab13010200.png',
    'fab13020000.png',
    'fab13020001.png',
    'fab13020004.png',
    'fab13020005.png',
    'fab13020100.png',
    'fab13020102.png',
    'fab13020200.png',
    'fab14010000.png',
    'fab14010001.png',
    'fab14010004.png',
    'fab14010005.png',
    'fab14010100.png',
    'fab14010102.png',
    'fab14010200.png',
    'fab14020000.png',
    'fab14020001.png',
    'fab14020004.png',
    'fab14020005.png',
    'fab14020100.png',
    'fab14020102.png',
    'fab14020200.png',
    'fab15010000.png',
    'fab15010001.png',
    'fab15010004.png',
    'fab15010005.png',
    'fab15010100.png',
    'fab15010102.png',
    'fab15010200.png',
    'fab15020000.png',
    'fab15020001.png',
    'fab15020004.png',
    'fab15020005.png',
    'fab15020100.png',
    'fab15020102.png',
    'fab15020200.png',
    'fab15110000.png',
    'fab15110001.png',
    'fab15110004.png',
    'fab15110005.png',
    'fab15110100.png',
    'fab15110102.png',
    'fab15110200.png',
    'fab15210000.png',
    'fab15210001.png',
    'fab15210004.png',
    'fab15210005.png',
    'fab15210100.png',
    'fab15210102.png',
    'fab15210200.png',
    'fab15220000.png',
    'fab15220001.png',
    'fab15220004.png',
    'fab15220005.png',
    'fab15220100.png',
    'fab15220102.png',
    'fab15220200.png',
    'fab17010004.png',
    'fab17010100.png',
    'fab17010102.png',
    'fab18010000.png',
    'fab18010001.png',
    'fab18010004.png',
    'fab18010005.png',
    'fab18010100.png',
    'fab18010102.png',
    'fab18010200.png',
    'fab18020000.png',
    'fab18020001.png',
    'fab18020004.png',
    'fab18020005.png',
    'fab18020100.png',
    'fab18020102.png',
    'fab18020200.png',
    'fab18110000.png',
    'fab18110001.png',
    'fab18110004.png',
    'fab18110005.png',
    'fab18110100.png',
    'fab18110102.png',
    'fab18110200.png',
    'fab18120000.png',
    'fab18120001.png',
    'fab18120004.png',
    'fab18120005.png',
    'fab18120100.png',
    'fab18120102.png',
    'fab18120200.png',
    'fab18210000.png',
    'fab18210001.png',
    'fab18210004.png',
    'fab18210005.png',
    'fab18210100.png',
    'fab18210102.png',
    'fab18210200.png',
    'fab18220000.png',
    'fab18220001.png',
    'fab18220004.png',
    'fab18220005.png',
    'fab18220100.png',
    'fab18220102.png',
    'fab18220200.png',
    'fab19010000.png',
    'fab19010001.png',
    'fab19010004.png',
    'fab19010005.png',
    'fab19010100.png',
    'fab19010102.png',
    'fab19010200.png',
    'fab19020000.png',
    'fab19020001.png',
    'fab19020004.png',
    'fab19020005.png',
    'fab19020100.png',
    'fab19020102.png',
    'fab19020200.png',
    'fab19110000.png',
    'fab19110001.png',
    'fab19110004.png',
    'fab19110005.png',
    'fab19110100.png',
    'fab19110102.png',
    'fab19110200.png',
    'fab19120000.png',
    'fab19120001.png',
    'fab19120004.png',
    'fab19120005.png',
    'fab19120100.png',
    'fab19120102.png',
    'fab19120200.png',
    'fab19210000.png',
    'fab19210001.png',
    'fab19210004.png',
    'fab19210005.png',
    'fab19210100.png',
    'fab19210102.png',
    'fab19210200.png',
    'fab19220000.png',
    'fab19220001.png',
    'fab19220004.png',
    'fab19220005.png',
    'fab19220100.png',
    'fab19220102.png',
    'fab19220200.png',
    'fab19310000.png',
    'fab19310001.png',
    'fab19310004.png',
    'fab19310005.png',
    'fab19310100.png',
    'fab19310102.png',
    'fab19310200.png',
    'fab19320000.png',
    'fab19320001.png',
    'fab19320004.png',
    'fab19320005.png',
    'fab19320100.png',
    'fab19320102.png',
    'fab19320200.png',
    'fab19410000.png',
    'fab19410001.png',
    'fab19410004.png',
    'fab19410005.png',
    'fab19410100.png',
    'fab19410102.png',
    'fab19410200.png',
    'fab19420000.png',
    'fab19420001.png',
    'fab19420004.png',
    'fab19420005.png',
    'fab19420100.png',
    'fab19420102.png',
    'fab19420200.png',
    'fab19510000.png',
    'fab19510001.png',
    'fab19510004.png',
    'fab19510005.png',
    'fab19510100.png',
    'fab19510102.png',
    'fab19510200.png',
    'fab19520000.png',
    'fab19520001.png',
    'fab19520004.png',
    'fab19520005.png',
    'fab19520100.png',
    'fab19520102.png',
    'fab19520200.png',
    'fab19610000.png',
    'fab19610001.png',
    'fab19610004.png',
    'fab19610005.png',
    'fab19610100.png',
    'fab19610102.png',
    'fab19610200.png',
    'fab19620000.png',
    'fab19620001.png',
    'fab19620004.png',
    'fab19620005.png',
    'fab19620100.png',
    'fab19620102.png',
    'fab19620200.png',
    'fab19710000.png',
    'fab19710001.png',
    'fab19710004.png',
    'fab19710005.png',
    'fab19710100.png',
    'fab19710102.png',
    'fab19710200.png',
    'fab19720000.png',
    'fab19720001.png',
    'fab19720004.png',
    'fab19720005.png',
    'fab19720100.png',
    'fab19720102.png',
    'fab19720200.png',
    'fab19810000.png',
    'fab19810001.png',
    'fab19810004.png',
    'fab19810005.png',
    'fab19810100.png',
    'fab19810102.png',
    'fab19810200.png',
    'fab19820000.png',
    'fab19820001.png',
    'fab19820004.png',
    'fab19820005.png',
    'fab19820100.png',
    'fab19820102.png',
    'fab19820200.png',
    'fab19910000.png',
    'fab19910001.png',
    'fab19910004.png',
    'fab19910005.png',
    'fab19910100.png',
    'fab19910102.png',
    'fab19910200.png',
    'fab19920000.png',
    'fab19920001.png',
    'fab19920004.png',
    'fab19920005.png',
    'fab19920100.png',
    'fab19920102.png',
    'fab19920200.png',
    'fab20010000.png',
    'fab20010001.png',
    'fab20010004.png',
    'fab20010005.png',
    'fab20010100.png',
    'fab20010102.png',
    'fab20010200.png',
    'fab20020000.png',
    'fab20020001.png',
    'fab20020004.png',
    'fab20020005.png',
    'fab20020100.png',
    'fab20020102.png',
    'fab20020200.png',
    'fab20110000.png',
    'fab20110001.png',
    'fab20110004.png',
    'fab20110005.png',
    'fab20110100.png',
    'fab20110102.png',
    'fab20110200.png',
    'fab20120000.png',
    'fab20120001.png',
    'fab20120004.png',
    'fab20120005.png',
    'fab20120100.png',
    'fab20120102.png',
    'fab20120200.png',
    'fab21010000.png',
    'fab21010001.png',
    'fab21010004.png',
    'fab21010005.png',
    'fab21010100.png',
    'fab21010102.png',
    'fab21010200.png',
    'fab21020000.png',
    'fab21020001.png',
    'fab21020004.png',
    'fab21020005.png',
    'fab21020100.png',
    'fab21020102.png',
    'fab21020200.png',
    'fab21110000.png',
    'fab21110001.png',
    'fab21110004.png',
    'fab21110005.png',
    'fab21110100.png',
    'fab21110102.png',
    'fab21110200.png',
    'fab21120000.png',
    'fab21120001.png',
    'fab21120004.png',
    'fab21120005.png',
    'fab21120100.png',
    'fab21120102.png',
    'fab21120200.png',
    'fab21410000.png',
    'fab21410001.png',
    'fab21410004.png',
    'fab21410005.png',
    'fab21410100.png',
    'fab21410102.png',
    'fab21410200.png',
    'fab21420000.png',
    'fab21420001.png',
    'fab21420004.png',
    'fab21420005.png',
    'fab21420100.png',
    'fab21420102.png',
    'fab21420200.png',
    'fab22310000.png',
    'fab22310001.png',
    'fab22310004.png',
    'fab22310005.png',
    'fab22310100.png',
    'fab22310102.png',
    'fab22310200.png',
    'fab22320000.png',
    'fab22320001.png',
    'fab22320004.png',
    'fab22320005.png',
    'fab22320100.png',
    'fab22320102.png',
    'fab22320200.png',
    'fab22710000.png',
    'fab22710001.png',
    'fab22710004.png',
    'fab22710005.png',
    'fab22710100.png',
    'fab22710102.png',
    'fab22710200.png',
    'fab22720000.png',
    'fab22720001.png',
    'fab22720004.png',
    'fab22720005.png',
    'fab22720100.png',
    'fab22720102.png',
    'fab22720200.png',
    'fab22810000.png',
    'fab22810001.png',
    'fab22810004.png',
    'fab22810005.png',
    'fab22810100.png',
    'fab22810102.png',
    'fab22810200.png',
    'fab22820000.png',
    'fab22820001.png',
    'fab22820004.png',
    'fab22820005.png',
    'fab22820100.png',
    'fab22820102.png',
    'fab22820200.png',
    'fab22910000.png',
    'fab22910001.png',
    'fab22910004.png',
    'fab22910005.png',
    'fab22910100.png',
    'fab22910102.png',
    'fab22910200.png',
    'fab22920000.png',
    'fab22920001.png',
    'fab22920004.png',
    'fab22920005.png',
    'fab22920100.png',
    'fab22920102.png',
    'fab22920200.png',
    'fab23010000.png',
    'fab23010001.png',
    'fab23010004.png',
    'fab23010005.png',
    'fab23010100.png',
    'fab23010102.png',
    'fab23010200.png',
    'fab23020000.png',
    'fab23020001.png',
    'fab23020004.png',
    'fab23020005.png',
    'fab23020100.png',
    'fab23020102.png',
    'fab23020200.png',
    'fab23110000.png',
    'fab23110001.png',
    'fab23110004.png',
    'fab23110005.png',
    'fab23110100.png',
    'fab23110102.png',
    'fab23110200.png',
    'fab23120000.png',
    'fab23120001.png',
    'fab23120004.png',
    'fab23120005.png',
    'fab23120100.png',
    'fab23120102.png',
    'fab23120200.png',
    'fab23410000.png',
    'fab23410001.png',
    'fab23410004.png',
    'fab23410005.png',
    'fab23410100.png',
    'fab23410102.png',
    'fab23410200.png',
    'fab23420000.png',
    'fab23420001.png',
    'fab23420004.png',
    'fab23420005.png',
    'fab23420100.png',
    'fab23420102.png',
    'fab23420200.png',
    'fab23510000.png',
    'fab23510001.png',
    'fab23510004.png',
    'fab23510005.png',
    'fab23510100.png',
    'fab23510102.png',
    'fab23510200.png',
    'fab23520000.png',
    'fab23520001.png',
    'fab23520004.png',
    'fab23520005.png',
    'fab23520100.png',
    'fab23520102.png',
    'fab23520200.png',
    'fab24010000.png',
    'fab24010001.png',
    'fab24010004.png',
    'fab24010005.png',
    'fab24010100.png',
    'fab24010102.png',
    'fab24010200.png',
    'fab24020000.png',
    'fab24020001.png',
    'fab24020004.png',
    'fab24020005.png',
    'fab24020100.png',
    'fab24020102.png',
    'fab24020200.png',
    'fab24110000.png',
    'fab24110001.png',
    'fab24110004.png',
    'fab24110005.png',
    'fab24110100.png',
    'fab24110102.png',
    'fab24110200.png',
    'fab24120000.png',
    'fab24120001.png',
    'fab24120004.png',
    'fab24120005.png',
    'fab24120100.png',
    'fab24120102.png',
    'fab24120200.png',
    'fab24210000.png',
    'fab24210001.png',
    'fab24210004.png',
    'fab24210005.png',
    'fab24210100.png',
    'fab24210102.png',
    'fab24210200.png',
    'fab24220000.png',
    'fab24220001.png',
    'fab24220004.png',
    'fab24220005.png',
    'fab24220100.png',
    'fab24220102.png',
    'fab24220200.png',
    'fab24310000.png',
    'fab24310001.png',
    'fab24310004.png',
    'fab24310005.png',
    'fab24310100.png',
    'fab24310102.png',
    'fab24310200.png',
    'fab24320000.png',
    'fab24320001.png',
    'fab24320004.png',
    'fab24320005.png',
    'fab24320100.png',
    'fab24320102.png',
    'fab24320200.png',
    'fab24410000.png',
    'fab24410001.png',
    'fab24410004.png',
    'fab24410005.png',
    'fab24410100.png',
    'fab24410102.png',
    'fab24410200.png',
    'fab24420000.png',
    'fab24420001.png',
    'fab24420004.png',
    'fab24420005.png',
    'fab24420100.png',
    'fab24420102.png',
    'fab24420200.png',
    'fab24510000.png',
    'fab24510001.png',
    'fab24510004.png',
    'fab24510005.png',
    'fab24510100.png',
    'fab24510102.png',
    'fab24510200.png',
    'fab24520000.png',
    'fab24520001.png',
    'fab24520004.png',
    'fab24520005.png',
    'fab24520100.png',
    'fab24520102.png',
    'fab24520200.png',
    'fab24710000.png',
    'fab24710001.png',
    'fab24710004.png',
    'fab24710005.png',
    'fab24710100.png',
    'fab24710102.png',
    'fab24710200.png',
    'fab24720000.png',
    'fab24720001.png',
    'fab24720004.png',
    'fab24720005.png',
    'fab24720100.png',
    'fab24720102.png',
    'fab24720200.png',
    'fab24810000.png',
    'fab24810001.png',
    'fab24810004.png',
    'fab24810005.png',
    'fab24810100.png',
    'fab24810102.png',
    'fab24810200.png',
    'fab24820000.png',
    'fab24820001.png',
    'fab24820004.png',
    'fab24820005.png',
    'fab24820100.png',
    'fab24820102.png',
    'fab24820200.png',
    'fab24910000.png',
    'fab24910001.png',
    'fab24910004.png',
    'fab24910005.png',
    'fab24910100.png',
    'fab24910102.png',
    'fab24910200.png',
    'fab24920000.png',
    'fab24920001.png',
    'fab24920004.png',
    'fab24920005.png',
    'fab24920100.png',
    'fab24920102.png',
    'fab24920200.png',
    'fab25010000.png',
    'fab25010001.png',
    'fab25010004.png',
    'fab25010005.png',
    'fab25010100.png',
    'fab25010102.png',
    'fab25010200.png',
    'fab25020000.png',
    'fab25020001.png',
    'fab25020004.png',
    'fab25020005.png',
    'fab25020100.png',
    'fab25020102.png',
    'fab25020200.png',
    'fab25110000.png',
    'fab25110001.png',
    'fab25110004.png',
    'fab25110005.png',
    'fab25110100.png',
    'fab25110102.png',
    'fab25110200.png',
    'fab25120000.png',
    'fab25120001.png',
    'fab25120004.png',
    'fab25120005.png',
    'fab25120100.png',
    'fab25120102.png',
    'fab25120200.png',
    'fab25210000.png',
    'fab25210001.png',
    'fab25210004.png',
    'fab25210005.png',
    'fab25210100.png',
    'fab25210102.png',
    'fab25210200.png',
    'fab25220000.png',
    'fab25220001.png',
    'fab25220004.png',
    'fab25220005.png',
    'fab25220100.png',
    'fab25220102.png',
    'fab25220200.png',
    'fab25510000.png',
    'fab25510001.png',
    'fab25510004.png',
    'fab25510005.png',
    'fab25510100.png',
    'fab25510102.png',
    'fab25510200.png',
    'fab25520000.png',
    'fab25520001.png',
    'fab25520004.png',
    'fab25520005.png',
    'fab25520100.png',
    'fab25520102.png',
    'fab25520200.png',
    'fab25520500.png',
    'fab25610000.png',
    'fab25610001.png',
    'fab25610004.png',
    'fab25610005.png',
    'fab25610100.png',
    'fab25610102.png',
    'fab25610200.png',
    'fab25620000.png',
    'fab25620001.png',
    'fab25620004.png',
    'fab25620005.png',
    'fab25620100.png',
    'fab25620102.png',
    'fab25620200.png',
    'fab25710000.png',
    'fab25710001.png',
    'fab25710004.png',
    'fab25710005.png',
    'fab25710100.png',
    'fab25710102.png',
    'fab25710200.png',
    'fab25720000.png',
    'fab25720001.png',
    'fab25720004.png',
    'fab25720005.png',
    'fab25720100.png',
    'fab25720102.png',
    'fab25720200.png',
    'fab25810000.png',
    'fab25810001.png',
    'fab25810004.png',
    'fab25810005.png',
    'fab25810100.png',
    'fab25810102.png',
    'fab25810200.png',
    'fab25820000.png',
    'fab25820004.png',
    'fab25820005.png',
    'fab25820100.png',
    'fab25820102.png',
    'fab25820200.png',
    'fab27010000.png',
    'fab27010001.png',
    'fab27010004.png',
    'fab27010005.png',
    'fab27010100.png',
    'fab27010102.png',
    'fab27010200.png',
    'fab27020000.png',
    'fab27020001.png',
    'fab27020004.png',
    'fab27020005.png',
    'fab27020100.png',
    'fab27020102.png',
    'fab27020200.png',
    'fab27110000.png',
    'fab27110001.png',
    'fab27110004.png',
    'fab27110005.png',
    'fab27110100.png',
    'fab27110102.png',
    'fab27110200.png',
    'fab27120000.png',
    'fab27120001.png',
    'fab27120004.png',
    'fab27120005.png',
    'fab27120100.png',
    'fab27120102.png',
    'fab27120200.png',
    'fab27210000.png',
    'fab27210001.png',
    'fab27210004.png',
    'fab27210005.png',
    'fab27210100.png',
    'fab27210102.png',
    'fab27210200.png',
    'fab27220000.png',
    'fab27220001.png',
    'fab27220004.png',
    'fab27220005.png',
    'fab27220100.png',
    'fab27220102.png',
    'fab27220200.png',
    'fab27310000.png',
    'fab27310001.png',
    'fab27310004.png',
    'fab27310005.png',
    'fab27310100.png',
    'fab27310102.png',
    'fab27310200.png',
    'fab27320000.png',
    'fab27320001.png',
    'fab27320004.png',
    'fab27320005.png',
    'fab27320100.png',
    'fab27320102.png',
    'fab27320200.png',
    'fab27410000.png',
    'fab27410001.png',
    'fab27410004.png',
    'fab27410005.png',
    'fab27410100.png',
    'fab27410102.png',
    'fab27410200.png',
    'fab27420000.png',
    'fab27420001.png',
    'fab27420004.png',
    'fab27420005.png',
    'fab27420100.png',
    'fab27420102.png',
    'fab27420200.png',
    'fab27510000.png',
    'fab27510001.png',
    'fab27510004.png',
    'fab27510005.png',
    'fab27510100.png',
    'fab27510102.png',
    'fab27510200.png',
    'fab27520000.png',
    'fab27520001.png',
    'fab27520004.png',
    'fab27520005.png',
    'fab27520100.png',
    'fab27520102.png',
    'fab27520200.png',
    'fab27610000.png',
    'fab27610001.png',
    'fab27610004.png',
    'fab27610005.png',
    'fab27610100.png',
    'fab27610102.png',
    'fab27610200.png',
    'fab27620000.png',
    'fab27620001.png',
    'fab27620004.png',
    'fab27620005.png',
    'fab27620100.png',
    'fab27620102.png',
    'fab27620200.png',
    'fab27710000.png',
    'fab27710001.png',
    'fab27710004.png',
    'fab27710005.png',
    'fab27710100.png',
    'fab27710102.png',
    'fab27710200.png',
    'fab27720000.png',
    'fab27720001.png',
    'fab27720004.png',
    'fab27720005.png',
    'fab27720100.png',
    'fab27720102.png',
    'fab27720200.png',
    'fab27810000.png',
    'fab27810001.png',
    'fab27810004.png',
    'fab27810005.png',
    'fab27810100.png',
    'fab27810102.png',
    'fab27810200.png',
    'fab27820000.png',
    'fab27820001.png',
    'fab27820004.png',
    'fab27820005.png',
    'fab27820100.png',
    'fab27820102.png',
    'fab27820200.png',
    'fab27910000.png',
    'fab27910001.png',
    'fab27910004.png',
    'fab27910005.png',
    'fab27910100.png',
    'fab27910102.png',
    'fab27910200.png',
    'fab27920000.png',
    'fab27920001.png',
    'fab27920004.png',
    'fab27920005.png',
    'fab27920100.png',
    'fab27920102.png',
    'fab27920200.png',
    'fab28010000.png',
    'fab28010001.png',
    'fab28010004.png',
    'fab28010005.png',
    'fab28010100.png',
    'fab28010102.png',
    'fab28010200.png',
    'fab28020000.png',
    'fab28020001.png',
    'fab28020004.png',
    'fab28020005.png',
    'fab28020100.png',
    'fab28020102.png',
    'fab28020200.png',
    'fab28110000.png',
    'fab28110001.png',
    'fab28110004.png',
    'fab28110005.png',
    'fab28110100.png',
    'fab28110102.png',
    'fab28110200.png',
    'fab28120000.png',
    'fab28120001.png',
    'fab28120004.png',
    'fab28120005.png',
    'fab28120100.png',
    'fab28120102.png',
    'fab28120200.png',
    'fab28210000.png',
    'fab28210001.png',
    'fab28210004.png',
    'fab28210005.png',
    'fab28210100.png',
    'fab28210102.png',
    'fab28210200.png',
    'fab28220000.png',
    'fab28220001.png',
    'fab28220004.png',
    'fab28220005.png',
    'fab28220100.png',
    'fab28220102.png',
    'fab28220200.png',
    'fab28310000.png',
    'fab28310001.png',
    'fab28310004.png',
    'fab28310005.png',
    'fab28310100.png',
    'fab28310102.png',
    'fab28310200.png',
    'fab28320000.png',
    'fab28320001.png',
    'fab28320004.png',
    'fab28320005.png',
    'fab28320100.png',
    'fab28320102.png',
    'fab28320200.png',
    'fab28410000.png',
    'fab28410001.png',
    'fab28410004.png',
    'fab28410005.png',
    'fab28410100.png',
    'fab28410102.png',
    'fab28410200.png',
    'fab28420000.png',
    'fab28420001.png',
    'fab28420004.png',
    'fab28420005.png',
    'fab28420100.png',
    'fab28420102.png',
    'fab28420200.png',
    'fab28510000.png',
    'fab28510001.png',
    'fab28510004.png',
    'fab28510005.png',
    'fab28510100.png',
    'fab28510102.png',
    'fab28510200.png',
    'fab28520000.png',
    'fab28520001.png',
    'fab28520004.png',
    'fab28520005.png',
    'fab28520100.png',
    'fab28520102.png',
    'fab28520200.png',
    'fab28610000.png',
    'fab28610001.png',
    'fab28610004.png',
    'fab28610005.png',
    'fab28610100.png',
    'fab28610102.png',
    'fab28610200.png',
    'fab28620000.png',
    'fab28620001.png',
    'fab28620004.png',
    'fab28620005.png',
    'fab28620100.png',
    'fab28620102.png',
    'fab28620200.png',
    'fab28710000.png',
    'fab28710001.png',
    'fab28710004.png',
    'fab28710005.png',
    'fab28710100.png',
    'fab28710102.png',
    'fab28710200.png',
    'fab28720000.png',
    'fab28720001.png',
    'fab28720004.png',
    'fab28720005.png',
    'fab28720100.png',
    'fab28720102.png',
    'fab28720200.png',
    'fab28810000.png',
    'fab28810001.png',
    'fab28810004.png',
    'fab28810005.png',
    'fab28810100.png',
    'fab28810102.png',
    'fab28810200.png',
    'fab28820000.png',
    'fab28820001.png',
    'fab28820004.png',
    'fab28820005.png',
    'fab28820100.png',
    'fab28820102.png',
    'fab28820200.png',
    'fab28910000.png',
    'fab28910001.png',
    'fab28910004.png',
    'fab28910005.png',
    'fab28910100.png',
    'fab28910102.png',
    'fab28910200.png',
    'fab28920000.png',
    'fab28920001.png',
    'fab28920004.png',
    'fab28920005.png',
    'fab28920100.png',
    'fab28920102.png',
    'fab28920200.png',
    'fab29010000.png',
    'fab29010001.png',
    'fab29010004.png',
    'fab29010005.png',
    'fab29010100.png',
    'fab29010102.png',
    'fab29010200.png',
    'fab29020000.png',
    'fab29020001.png',
    'fab29020004.png',
    'fab29020005.png',
    'fab29020100.png',
    'fab29020102.png',
    'fab29020200.png',
    'fab29110000.png',
    'fab29110001.png',
    'fab29110004.png',
    'fab29110005.png',
    'fab29110100.png',
    'fab29110102.png',
    'fab29110200.png',
    'fab29120000.png',
    'fab29120001.png',
    'fab29120004.png',
    'fab29120005.png',
    'fab29120100.png',
    'fab29120102.png',
    'fab29120200.png',
    'fab29210000.png',
    'fab29210001.png',
    'fab29210004.png',
    'fab29210005.png',
    'fab29210100.png',
    'fab29210102.png',
    'fab29210200.png',
    'fab29220000.png',
    'fab29220001.png',
    'fab29220004.png',
    'fab29220005.png',
    'fab29220100.png',
    'fab29220102.png',
    'fab29220200.png',
    'fab29310000.png',
    'fab29310001.png',
    'fab29310004.png',
    'fab29310005.png',
    'fab29310100.png',
    'fab29310102.png',
    'fab29310200.png',
    'fab29320000.png',
    'fab29320001.png',
    'fab29320004.png',
    'fab29320005.png',
    'fab29320100.png',
    'fab29320102.png',
    'fab29320200.png',
    'fab29410000.png',
    'fab29410001.png',
    'fab29410004.png',
    'fab29410005.png',
    'fab29410100.png',
    'fab29410102.png',
    'fab29410200.png',
    'fab29420000.png',
    'fab29420001.png',
    'fab29420004.png',
    'fab29420005.png',
    'fab29420100.png',
    'fab29420102.png',
    'fab29420200.png',
    'fab29510000.png',
    'fab29510001.png',
    'fab29510004.png',
    'fab29510005.png',
    'fab29510100.png',
    'fab29510102.png',
    'fab29510200.png',
    'fab29520000.png',
    'fab29520001.png',
    'fab29520004.png',
    'fab29520005.png',
    'fab29520100.png',
    'fab29520102.png',
    'fab29520200.png',
    'fab31010000.png',
    'fab31010001.png',
    'fab31010004.png',
    'fab31010100.png',
    'fab31010102.png',
    'fab31010200.png',
    'fab31020000.png',
    'fab31020001.png',
    'fab31020004.png',
    'fab31020005.png',
    'fab31020100.png',
    'fab31020102.png',
    'fab31020200.png',
    'fab31050005.png',
    'fab31050100.png',
    'fab31050200.png',
    'fab32010000.png',
    'fab32010001.png',
    'fab32010004.png',
    'fab32010100.png',
    'fab32010102.png',
    'fab32010200.png',
    'fab32020000.png',
    'fab32020001.png',
    'fab32020004.png',
    'fab32020005.png',
    'fab32020100.png',
    'fab32020102.png',
    'fab32020200.png',
    'fab32050005.png',
    'fab32050100.png',
    'fab32050200.png',
    'fab33010000.png',
    'fab33010001.png',
    'fab33010004.png',
    'fab33010100.png',
    'fab33010102.png',
    'fab33010200.png',
    'fab33020000.png',
    'fab33020001.png',
    'fab33020004.png',
    'fab33020005.png',
    'fab33020100.png',
    'fab33020102.png',
    'fab33020200.png',
    'fab33050005.png',
    'fab33050100.png',
    'fab33050200.png',
    'fab35010000.png',
    'fab35010001.png',
    'fab35010004.png',
    'fab35010005.png',
    'fab35010100.png',
    'fab35010102.png',
    'fab35010200.png',
    'fab35020000.png',
    'fab35020001.png',
    'fab35020004.png',
    'fab35020005.png',
    'fab35020100.png',
    'fab35020102.png',
    'fab35020200.png',
    'fab36010000.png',
    'fab36010001.png',
    'fab36010004.png',
    'fab36010005.png',
    'fab36010100.png',
    'fab36010102.png',
    'fab36010200.png',
    'fab36020000.png',
    'fab36020001.png',
    'fab36020004.png',
    'fab36020005.png',
    'fab36020100.png',
    'fab36020102.png',
    'fab36020200.png',
    'fab36920000.png',
    'fab36920001.png',
    'fab36920004.png',
    'fab36920005.png',
    'fab36920100.png',
    'fab36920102.png',
    'fab36920200.png',
    'fab37010000.png',
    'fab37010001.png',
    'fab37010004.png',
    'fab37010005.png',
    'fab37010100.png',
    'fab37010102.png',
    'fab37010200.png',
    'fab37020000.png',
    'fab37020001.png',
    'fab37020004.png',
    'fab37020005.png',
    'fab37020100.png',
    'fab37020102.png',
    'fab37020200.png',
    'fab38010000.png',
    'fab38010001.png',
    'fab38010004.png',
    'fab38010005.png',
    'fab38010100.png',
    'fab38010102.png',
    'fab38010200.png',
    'fab38020000.png',
    'fab38020001.png',
    'fab38020002.png',
    'fab38020004.png',
    'fab38020005.png',
    'fab38020100.png',
    'fab38020102.png',
    'fab38020200.png',
    'fab39010000.png',
    'fab39010001.png',
    'fab39010004.png',
    'fab39010005.png',
    'fab39010100.png',
    'fab39010102.png',
    'fab39010200.png',
    'fab39020000.png',
    'fab39020001.png',
    'fab39020004.png',
    'fab39020005.png',
    'fab39020100.png',
    'fab39020102.png',
    'fab39020200.png',
    'fab40010000.png',
    'fab40010001.png',
    'fab40010004.png',
    'fab40010005.png',
    'fab40010100.png',
    'fab40010102.png',
    'fab40010200.png',
    'fab40020000.png',
    'fab40020001.png',
    'fab40020004.png',
    'fab40020005.png',
    'fab40020100.png',
    'fab40020102.png',
    'fab40020200.png',
    'fab41010000.png',
    'fab41010001.png',
    'fab41010004.png',
    'fab41010005.png',
    'fab41010100.png',
    'fab41010102.png',
    'fab41010200.png',
    'fab41020000.png',
    'fab41020001.png',
    'fab41020004.png',
    'fab41020005.png',
    'fab41020100.png',
    'fab41020102.png',
    'fab41020200.png',
    'fab42010000.png',
    'fab42010001.png',
    'fab42010004.png',
    'fab42010005.png',
    'fab42010100.png',
    'fab42010102.png',
    'fab42010200.png',
    'fab42020000.png',
    'fab42020001.png',
    'fab42020004.png',
    'fab42020005.png',
    'fab42020100.png',
    'fab42020102.png',
    'fab42020200.png',
    'fab43010000.png',
    'fab43010001.png',
    'fab43010004.png',
    'fab43010005.png',
    'fab43010100.png',
    'fab43010102.png',
    'fab43010200.png',
    'fab45010000.png',
    'fab45010001.png',
    'fab45010004.png',
    'fab45010005.png',
    'fab45010100.png',
    'fab45010102.png',
    'fab45010200.png',
    'fab45020000.png',
    'fab45020001.png',
    'fab45020004.png',
    'fab45020005.png',
    'fab45020100.png',
    'fab45020102.png',
    'fab45020200.png',
    'fab47010000.png',
    'fab47010001.png',
    'fab47010004.png',
    'fab47010005.png',
    'fab47010100.png',
    'fab47010102.png',
    'fab47010200.png',
    'fab47020000.png',
    'fab47020001.png',
    'fab47020004.png',
    'fab47020005.png',
    'fab47020100.png',
    'fab47020102.png',
    'fab47020200.png',
    'fab48010000.png',
    'fab48010001.png',
    'fab48010004.png',
    'fab48010005.png',
    'fab48010100.png',
    'fab48010102.png',
    'fab48010200.png',
    'fab48020000.png',
    'fab48020001.png',
    'fab48020004.png',
    'fab48020005.png',
    'fab48020100.png',
    'fab48020102.png',
    'fab48020200.png',
    'fab49010000.png',
    'fab49010001.png',
    'fab49010004.png',
    'fab49010005.png',
    'fab49010100.png',
    'fab49010102.png',
    'fab49010200.png',
    'fab49020000.png',
    'fab49020001.png',
    'fab49020004.png',
    'fab49020005.png',
    'fab49020100.png',
    'fab49020102.png',
    'fab49020200.png',
    'fab50010000.png',
    'fab50010001.png',
    'fab50010004.png',
    'fab50010005.png',
    'fab50010100.png',
    'fab50010102.png',
    'fab50010200.png',
    'fab99990000.png',
    'fab99990004.png',
    'fab99990100.png',
    'fab99990102.png',
)

fab_pac_files = []

python3 = find_program('python3')

foreach fab_png : fab_png_files
    pac = custom_target(fs.name(fab_png).replace('.png', '.pac_'),
        input: fab_png,
        output: '@BASENAME@.pac_',
        command: [
            python3,
            image_py,
            '@INPUT@',
            '-t', 'PSCM',
            '-c', '@OUTPUT@',
        ]
    )
    fab_pac_files += pac
endforeach
