mbd_c_png_files = files(
    'mbd_c00000001.png',
    'mbd_c00000002.png',
    'mbd_c00000003.png',
    'mbd_c00000010.png',
    'mbd_c00000011.png',
    'mbd_c00000012.png',
    'mbd_c00000020.png',
    'mbd_c00000021.png',
    'mbd_c00000022.png',
    'mbd_c00000023.png',
    'mbd_c00000030.png',
    'mbd_c00000031.png',
    'mbd_c00000051.png',
    'mbd_c00000052.png',
    'mbd_c00000053.png',
    'mbd_c00000054.png',
    'mbd_c00000055.png',
    'mbd_c00000056.png',
    'mbd_c00000057.png',
    'mbd_c00000058.png',
    'mbd_c00000059.png',
    'mbd_c00000060.png',
    'mbd_c00000061.png',
    'mbd_c00000062.png',
    'mbd_c00000063.png',
    'mbd_c00000064.png',
    'mbd_c00000065.png',
    'mbd_c00000066.png',
    'mbd_c00000067.png',
    'mbd_c00000068.png',
    'mbd_c00000069.png',
    'mbd_c00000070.png',
    'mbd_c00000071.png',
    'mbd_c00000072.png',
    'mbd_c00000073.png',
    'mbd_c00000074.png',
    'mbd_c00000075.png',
    'mbd_c00000076.png',
    'mbd_c00000077.png',
    'mbd_c00000078.png',
    'mbd_c00000079.png',
    'mbd_c00000080.png',
    'mbd_c00000081.png',
    'mbd_c00000101.png',
    'mbd_c00000102.png',
    'mbd_c00000103.png',
    'mbd_c00000104.png',
    'mbd_c00000105.png',
    'mbd_c00000106.png',
    'mbd_c00000107.png',
    'mbd_c00000108.png',
    'mbd_c00000109.png',
    'mbd_c00000110.png',
    'mbd_c00000111.png',
    'mbd_c00000112.png',
    'mbd_c00000113.png',
    'mbd_c00000114.png',
    'mbd_c00000115.png',
    'mbd_c00000116.png',
    'mbd_c00000117.png',
    'mbd_c00000118.png',
    'mbd_c00000119.png',
    'mbd_c00000120.png',
    'mbd_c00000121.png',
    'mbd_c00000122.png',
    'mbd_c00000123.png',
    'mbd_c00000124.png',
    'mbd_c00000125.png',
    'mbd_c00000126.png',
    'mbd_c00000127.png',
    'mbd_c00000128.png',
    'mbd_c00000129.png',
    'mbd_c00000130.png',
    'mbd_c00000131.png',
    'mbd_c00000132.png',
    'mbd_c00000133.png',
    'mbd_c00000134.png',
    'mbd_c00000135.png',
    'mbd_c00000136.png',
    'mbd_c00000137.png',
    'mbd_c00000138.png',
    'mbd_c00000139.png',
    'mbd_c00000140.png',
    'mbd_c00000141.png',
    'mbd_c00000142.png',
    'mbd_c00000143.png',
    'mbd_c00000144.png',
    'mbd_c00000145.png',
    'mbd_c00000146.png',
    'mbd_c00000147.png',
    'mbd_c00000148.png',
    'mbd_c00000149.png',
    'mbd_c00000150.png',
    'mbd_c00000151.png',
    'mbd_c00000152.png',
    'mbd_c00000153.png',
    'mbd_c00000154.png',
    'mbd_c00000155.png',
    'mbd_c00000156.png',
    'mbd_c00000157.png',
    'mbd_c00000158.png',
    'mbd_c00000159.png',
    'mbd_c00000160.png',
    'mbd_c00000161.png',
    'mbd_c00000162.png',
    'mbd_c00000163.png',
    'mbd_c00000164.png',
    'mbd_c00000165.png',
    'mbd_c00000166.png',
    'mbd_c00000167.png',
    'mbd_c00000168.png',
    'mbd_c00000169.png',
    'mbd_c00000170.png',
    'mbd_c00000171.png',
    'mbd_c00000172.png',
    'mbd_c00000173.png',
    'mbd_c00000174.png',
    'mbd_c00000175.png',
    'mbd_c00000176.png',
    'mbd_c00000177.png',
    'mbd_c00000178.png',
    'mbd_c00000179.png',
    'mbd_c00000180.png',
    'mbd_c00000181.png',
    'mbd_c00000182.png',
    'mbd_c00000183.png',
    'mbd_c00000184.png',
    'mbd_c00000185.png',
    'mbd_c00000186.png',
    'mbd_c00000187.png',
    'mbd_c00000188.png',
    'mbd_c00000189.png',
    'mbd_c00000190.png',
    'mbd_c00000191.png',
    'mbd_c00000192.png',
    'mbd_c00000193.png',
    'mbd_c00000194.png',
    'mbd_c00000195.png',
    'mbd_c00000196.png',
    'mbd_c00000197.png',
    'mbd_c00000198.png',
    'mbd_c00000199.png',
    'mbd_c00000200.png',
    'mbd_c00000201.png',
    'mbd_c00000202.png',
    'mbd_c00000203.png',
    'mbd_c00000204.png',
    'mbd_c00000205.png',
    'mbd_c00000206.png',
    'mbd_c00000207.png',
    'mbd_c00000208.png',
    'mbd_c00000209.png',
    'mbd_c00000210.png',
    'mbd_c00000211.png',
    'mbd_c00000212.png',
    'mbd_c00000213.png',
    'mbd_c00000214.png',
    'mbd_c00000215.png',
    'mbd_c00000216.png',
    'mbd_c00000217.png',
    'mbd_c00000218.png',
    'mbd_c00000219.png',
    'mbd_c00000220.png',
    'mbd_c00000221.png',
    'mbd_c00000222.png',
    'mbd_c00000223.png',
    'mbd_c00000224.png',
    'mbd_c00000225.png',
    'mbd_c00000226.png',
    'mbd_c00000227.png',
    'mbd_c00000228.png',
    'mbd_c00000229.png',
    'mbd_c00000230.png',
    'mbd_c00000231.png',
    'mbd_c00000232.png',
    'mbd_c00000233.png',
    'mbd_c00000234.png',
    'mbd_c00000235.png',
    'mbd_c00000236.png',
    'mbd_c00000237.png',
    'mbd_c00000238.png',
    'mbd_c00000239.png',
    'mbd_c00000240.png',
    'mbd_c00000241.png',
    'mbd_c00000242.png',
    'mbd_c00000243.png',
    'mbd_c00000244.png',
    'mbd_c00000245.png',
    'mbd_c00000246.png',
    'mbd_c00000247.png',
    'mbd_c00000248.png',
    'mbd_c00000249.png',
    'mbd_c00000250.png',
    'mbd_c00000251.png',
    'mbd_c00000252.png',
    'mbd_c00000253.png',
    'mbd_c00000254.png',
    'mbd_c00000255.png',
    'mbd_c00000256.png',
    'mbd_c00000257.png',
    'mbd_c00000258.png',
    'mbd_c00000259.png',
    'mbd_c00000260.png',
    'mbd_c00000261.png',
    'mbd_c00000262.png',
    'mbd_c00000263.png',
    'mbd_c00000264.png',
    'mbd_c00000265.png',
    'mbd_c00000266.png',
    'mbd_c00000267.png',
    'mbd_c00000268.png',
    'mbd_c00000269.png',
    'mbd_c00000270.png',
    'mbd_c00000271.png',
    'mbd_c00000272.png',
    'mbd_c00000273.png',
    'mbd_c00000274.png',
    'mbd_c00000275.png',
    'mbd_c00000276.png',
    'mbd_c00000277.png',
    'mbd_c00000278.png',
    'mbd_c00000279.png',
    'mbd_c00000280.png',
    'mbd_c00000281.png',
    'mbd_c00000282.png',
    'mbd_c00000283.png',
    'mbd_c00000284.png',
    'mbd_c00000285.png',
    'mbd_c00000286.png',
    'mbd_c00000287.png',
    'mbd_c00000288.png',
    'mbd_c00000289.png',
    'mbd_c00000290.png',
    'mbd_c00000291.png',
    'mbd_c00000292.png',
    'mbd_c00000293.png',
    'mbd_c00000294.png',
    'mbd_c00000295.png',
    'mbd_c00000296.png',
    'mbd_c00000297.png',
    'mbd_c00000298.png',
    'mbd_c00000299.png',
    'mbd_c00000300.png',
    'mbd_c00000301.png',
    'mbd_c00000302.png',
    'mbd_c00000303.png',
    'mbd_c00000304.png',
    'mbd_c00000305.png',
    'mbd_c00000306.png',
    'mbd_c00000307.png',
    'mbd_c00000308.png',
    'mbd_c00000309.png',
    'mbd_c00000310.png',
    'mbd_c00000311.png',
    'mbd_c00000312.png',
    'mbd_c00000313.png',
    'mbd_c00000314.png',
    'mbd_c00000315.png',
    'mbd_c00000316.png',
    'mbd_c00000317.png',
    'mbd_c00000318.png',
    'mbd_c00000319.png',
    'mbd_c00000320.png',
    'mbd_c00000321.png',
    'mbd_c00000322.png',
    'mbd_c00000323.png',
    'mbd_c00000324.png',
    'mbd_c00000325.png',
    'mbd_c00000326.png',
    'mbd_c00000327.png',
    'mbd_c00000328.png',
    'mbd_c00000329.png',
    'mbd_c00000330.png',
    'mbd_c00000331.png',
    'mbd_c00000332.png',
    'mbd_c00000333.png',
    'mbd_c00000334.png',
    'mbd_c00000335.png',
    'mbd_c00000336.png',
    'mbd_c00000337.png',
    'mbd_c00000338.png',
    'mbd_c00000339.png',
    'mbd_c00000340.png',
    'mbd_c00000341.png',
    'mbd_c00000342.png',
    'mbd_c00000343.png',
    'mbd_c00000344.png',
    'mbd_c00000345.png',
    'mbd_c00000346.png',
    'mbd_c00000347.png',
    'mbd_c00000348.png',
    'mbd_c00000349.png',
    'mbd_c00000350.png',
    'mbd_c00000351.png',
    'mbd_c00000352.png',
    'mbd_c00000353.png',
    'mbd_c00000354.png',
    'mbd_c00000355.png',
    'mbd_c00000356.png',
    'mbd_c00000357.png',
    'mbd_c00000358.png',
    'mbd_c00000359.png',
    'mbd_c00000360.png',
    'mbd_c00000361.png',
    'mbd_c00000362.png',
    'mbd_c00000363.png',
    'mbd_c00000364.png',
    'mbd_c00000365.png',
    'mbd_c00000366.png',
    'mbd_c00000367.png',
    'mbd_c00000368.png',
    'mbd_c00000369.png',
    'mbd_c00000370.png',
    'mbd_c00000371.png',
    'mbd_c00000372.png',
    'mbd_c00000373.png',
    'mbd_c00000374.png',
    'mbd_c00000375.png',
    'mbd_c00000376.png',
    'mbd_c00000377.png',
    'mbd_c00000378.png',
    'mbd_c00000379.png',
    'mbd_c00000380.png',
    'mbd_c00000381.png',
    'mbd_c00000382.png',
    'mbd_c00000383.png',
    'mbd_c00000384.png',
    'mbd_c00000385.png',
    'mbd_c00000386.png',
    'mbd_c00000387.png',
    'mbd_c00000388.png',
    'mbd_c00000389.png',
    'mbd_c00000390.png',
    'mbd_c00000391.png',
    'mbd_c00000392.png',
    'mbd_c00000393.png',
    'mbd_c00000394.png',
    'mbd_c00000395.png',
    'mbd_c00000401.png',
    'mbd_c00000402.png',
    'mbd_c00000403.png',
    'mbd_c00000404.png',
    'mbd_c00000405.png',
    'mbd_c00000406.png',
    'mbd_c00000407.png',
    'mbd_c00000408.png',
    'mbd_c00000409.png',
    'mbd_c00000410.png',
    'mbd_c00000411.png',
    'mbd_c00000412.png',
    'mbd_c00000413.png',
    'mbd_c00000414.png',
    'mbd_c00000415.png',
    'mbd_c00000416.png',
    'mbd_c00000417.png',
    'mbd_c00000418.png',
    'mbd_c00000419.png',
    'mbd_c00000420.png',
    'mbd_c00000421.png',
    'mbd_c00000422.png',
    'mbd_c00000423.png',
    'mbd_c00000424.png',
    'mbd_c00000425.png',
    'mbd_c00000426.png',
    'mbd_c00000427.png',
    'mbd_c00000428.png',
    'mbd_c00000429.png',
    'mbd_c00000430.png',
    'mbd_c00000431.png',
    'mbd_c00000432.png',
    'mbd_c00000433.png',
    'mbd_c00000434.png',
    'mbd_c00000435.png',
    'mbd_c00000436.png',
    'mbd_c00000437.png',
    'mbd_c00000438.png',
    'mbd_c00000439.png',
    'mbd_c00000440.png',
    'mbd_c00000441.png',
    'mbd_c00000442.png',
    'mbd_c00000443.png',
    'mbd_c00000444.png',
    'mbd_c00000445.png',
    'mbd_c00000446.png',
    'mbd_c00000447.png',
    'mbd_c00000451.png',
    'mbd_c00000452.png',
    'mbd_c00000453.png',
    'mbd_c00000454.png',
    'mbd_c00000455.png',
    'mbd_c00000456.png',
    'mbd_c00000457.png',
    'mbd_c00000458.png',
    'mbd_c00000459.png',
    'mbd_c00000460.png',
    'mbd_c00000461.png',
    'mbd_c00000462.png',
    'mbd_c00000463.png',
    'mbd_c00000464.png',
    'mbd_c00000471.png',
    'mbd_c00000472.png',
)

mbd_c_pac_files = []

python3 = find_program('python3')

foreach mbd_c_png : mbd_c_png_files
    pac = custom_target(fs.name(mbd_c_png).replace('.png', '.pac'),
        input: mbd_c_png,
        output: '@BASENAME@.pac',
        command: [
            python3,
            image_py,
            '@INPUT@',
            '-t', 'PSC',
            '-c', '@OUTPUT@',
        ]
    )
    mbd_c_pac_files += pac
endforeach
