efct_files = files(
    'ef_c001a.PLT',
    'ef_c002a.pac',
    'ef_c004a.PLT',
    'ef_c007a.PLT',
    'ef_c011a.PLT',
    'ef_c013a.PLT',
    'ef_c016a.PLT',
    'ef_c018a.PLT',
    'ef_c001a.pac',
    'ef_c003a.PLT',
    'ef_c005a.PLT',
    'ef_c008a.PLT',
    'ef_c011a.pac',
    'ef_c014a.PLT',
    'ef_c016a.pac',
    'ef_c019a.PLT',
    'ef_c002a.PLT',
    'ef_c003a.pac',
    'ef_c006a.PLT',
    'ef_c009a.PLT',
    'ef_c012a.PLT',
    'ef_c015a.PLT',
    'ef_c017a.PLT',
    'ef_c020a.PLT',
)
